# Generated by Django 3.0.4 on 2020-04-25 16:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivorceComplaint',
            fields=[
                ('dc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('o_name', models.CharField(max_length=128, verbose_name='Complainant Name')),
                ('o_email', models.EmailField(max_length=64, verbose_name='Complainant Email')),
                ('o_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Complainant No')),
                ('o_state', models.CharField(max_length=32, verbose_name='Complainant Name')),
                ('o_city', models.CharField(max_length=32, verbose_name='Complainant City')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=8, verbose_name='Gender')),
                ('age', models.CharField(choices=[('20-25', '20-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56+', '56+')], default='20-25', max_length=8, verbose_name='Complainant Age')),
                ('year', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='Year of Marriage')),
                ('get_div', models.CharField(choices=[('YOU', 'YOU'), ('YOUR PARTNER', 'YOUR PARTNER')], default='YOU', max_length=16, verbose_name='Who wants Divorce')),
                ('sure_div', models.CharField(choices=[('I AM NOT SURE', 'I AM NOT SURE'), ('I AM SURE, BUT NEED GUIDANCE', 'I AM SURE, BUT NEED GUIDANCE')], default='I AM NOT SURE', max_length=64, verbose_name='How sure you are to get divorce')),
                ('court_div', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3, verbose_name='Divorce filed at court')),
                ('children', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=2, verbose_name='No. of children')),
                ('c_reln', models.CharField(choices=[('LOW CONFLICT', 'LOW CONFLICT'), ('HIGH CONFLICT', 'HIGH CONFLICT'), ('SUSPICIOUS', 'SUSPICIOUS')], default='LOW CONFLICT', max_length=16, verbose_name='Current relation status')),
                ('o_emp', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=4, verbose_name='Complainant employed')),
                ('p_emp', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=4, verbose_name='Partner employed')),
                ('c_description', models.TextField(max_length=4056, validators=[django.core.validators.MinLengthValidator(30)], verbose_name='Complainant Description')),
                ('c_document', models.FileField(blank=True, null=True, upload_to='divorce/', verbose_name='Complaint related documents')),
                ('c_filed', models.DateField(auto_now_add=True, verbose_name='Complaint filed date')),
                ('c_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000000, null=True, verbose_name='Complaint Amount')),
                ('p_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('p_status', models.BooleanField(default=0, verbose_name='Payment Status')),
                ('new_cid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Order ID')),
                ('txn_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Transaction ID')),
                ('update_flag', models.BooleanField(default=0, verbose_name='Information Updated')),
                ('admin_reply', models.TextField(blank=True, max_length=4056, null=True, validators=[django.core.validators.MinLengthValidator(30)], verbose_name='Update Complaint Status')),
                ('admin_document', models.FileField(blank=True, null=True, upload_to='admin/divorce/', verbose_name='Attach documents')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
