# Generated by Django 3.0.4 on 2020-04-25 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticcomplaint',
            name='admin_reply',
            field=models.TextField(blank=True, max_length=4056, null=True, verbose_name='Update Complaint Status'),
        ),
        migrations.AlterField(
            model_name='domesticcomplaint',
            name='doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Complainant Name'),
        ),
    ]
